/**
 * Static map of Firestore party slug → exact filename in /public/parties/.
 *
 * Each entry is the ONLY URL tried — no cascade, no 404 probing.
 * Extend this map whenever a new party image is added.
 */
const PARTY_ICON_MAP: Record<string, string> = {
  // ── Slugs generated by nameToSlug() ──────────────────────────────────────
  "ahora-nacion-an":                                           "ahoranacion-an.jpeg",
  "alianza-electoral-fuerza-y-libertad":                       "alianzaelectoralfuerzaylibertad.jpeg",
  "alianza-electoral-unidad-nacional":                         "alianzaelectoralunidadnacional.jpeg",
  "alianza-electoral-venceremos":                              "alianzaelectoralvenceremos.jpeg",
  "alianza-para-el-progreso":                                  "alianzaparaelprogreso.jpeg",
  "avanza-pais-partido-de-integracion-social":                 "avanzapais-partidodeintegracionsocial.jpeg",
  "fe-en-el-peru":                                            "feenelperu.jpeg",
  "frente-popular-agricola-fia-del-peru":                      "frentepopularagricolafiadelperu.png",
  "fuerza-popular":                                           "fuerzapopular.jpeg",
  "juntos-por-el-peru":                                       "juntosporelperu.jpeg",
  "libertad-popular":                                         "libertadpopular.jpeg",
  "partido-aprista-peruano":                                   "partidoapristaperuano.jpeg",
  "partido-ciudadanos-por-el-peru":                            "partidociudadanosporelperu.jpeg",
  "partido-civico-obras":                                      "partidocivicoobras.jpeg",
  "partido-del-buen-gobierno":                                 "partidodelbuengobierno.jpeg",
  "partido-de-los-trabajadores-y-emprendedores-pte-peru":      "partidodelostrabajadoresyemprendedorespte-peru.jpeg",
  "partido-democrata-unido-peru":                              "partidodemocrataunidoperu.jpeg",
  "partido-democrata-verde":                                   "partidodemocrataverde.jpeg",
  "partido-democratico-federal":                               "partidodemocraticofederal.jpeg",
  "partido-democratico-somos-peru":                            "partidodemocraticosomosperu.jpeg",
  "partido-frente-de-la-esperanza-2021":                       "partidofrentedelaesperanza2021.jpeg",
  "partido-morado":                                           "partidomorado.jpeg",
  "partido-pais-para-todos":                                   "partidopaisparatodos.jpeg",
  "partido-patriotico-del-peru":                               "partidopatrioticodelperu.jpeg",
  "partido-politico-cooperacion-popular":                      "partidopoliticocooperacionpopular.jpeg",
  "partido-politico-integridad-democratica":                   "partidopoliticointegridaddemocratica.jpeg",
  "partido-politico-nacional-peru-libre":                      "partidopoliticonacionalperulibre.jpeg",
  "partido-politico-peru-accion":                              "partido-politico-peru-accion.jpeg",
  "partido-politico-peru-primero":                             "partidopoliticoperuprimero.jpeg",
  "partido-politico-prin":                                     "partidopoliticoprin.jpeg",
  "partido-sicreo":                                           "partidosicreo.jpeg",
  "peru-moderno":                                             "perumoderno.jpeg",
  "podemos-peru":                                             "podemosperu.jpeg",
  "primero-la-gente-comunidad-ecologia-libertad-y-progreso":   "primerolagente-comunidadecologialibertadyprogreso.jpeg",
  "progresemos":                                              "PROGRESEMOS.jpeg",
  "renovacion-popular":                                       "renovacionpopular.jpeg",
  "salvemos-al-peru":                                         "salvemosalperu.jpeg",
  "un-camino-diferente":                                      "uncaminodiferente.jpeg",
  // ── Additional slug aliases (actual Firestore slugs that differ from filename) ──
  "alianza-unidad-nacional":                                   "alianzaelectoralunidadnacional.jpeg",
  "frente-popular-agricola-del-peru":                          "frentepopularagricolafiadelperu.png",
  "partido-politico-fe-en-el-peru":                            "feenelperu.jpeg",
  "fuerza-y-libertad":                                        "alianzaelectoralfuerzaylibertad.jpeg",
  "partido-politico-libertad-popular":                         "libertadpopular.jpeg",
  "partido-politico-peru-moderno":                             "perumoderno.jpeg",
}

export interface PartyIconInfo {
  slug: string
  /** If set, overrides the map lookup (explicit filename stored in Firestore). */
  iconFileName?: string | null
}

/**
 * Returns the single resolved path for a party icon, or `null` if unknown.
 *
 * Priority:
 *  1. `iconFileName` from Firestore (explicit, most reliable).
 *  2. Static `PARTY_ICON_MAP` lookup by slug.
 *  3. `null`  →  component renders a fallback UI, zero network request.
 */
export function getPartyIconPath(party: PartyIconInfo): string | null {
  if (party.iconFileName) return `/parties/${party.iconFileName}`
  const file = PARTY_ICON_MAP[party.slug]
  return file ? `/parties/${file}` : null
}
